# Generated by Django 3.2.9 on 2021-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('orchestra_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_musicians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_orchestra',
                'managed': False,
            },
        ),
    ]
